#!/bin/sh
# Statring selected composition with HSUSB enabled.

export KERNEL=`uname -r`
if [ -f /usr/lib/modules/$KERNEL/kernel/drivers/usb/gadget/ci13xxx_msm.ko ]; then
        insmod /usr/lib/modules/$KERNEL/kernel/drivers/usb/gadget/ci13xxx_msm.ko
        echo android_usb > /sys/bus/platform/drivers/android_usb/bind
fi

if [ -d /sys/class/android_usb/android0 ]
then
	echo hsusb > /sys/devices/platform/usb_bam/enable
	/usr/bin/usb/boot_composition n
fi


