#!/bin/sh
# Statring selected composition with HSIC enabled.
export KERNEL=`uname -r`
if [ -f /usr/lib/modules/$KERNEL/kernel/drivers/usb/gadget/ci13xxx_msm_hsic.ko ]; then
        insmod /usr/lib/modules/$KERNEL/kernel/drivers/usb/gadget/ci13xxx_msm_hsic.ko
        echo android_usb > /sys/bus/platform/drivers/android_usb/bind
fi

if [ -d /sys/class/android_usb/android0 ]
then
	echo hsic > /sys/devices/platform/usb_bam/enable
	/usr/bin/usb/boot_composition y
fi

