#!/bin/sh

# DESCRIPTION: DIAG + SERIAL + QMI_RMNET + Mass Storage [Android] + Audio [Android]

echo "Switching to composition number 0x900A"

if [ "$1" = "y" ]; then
	num="1"
	mode="hsic"
else
	num="0"
	mode="hsusb"
fi

echo $mode > /sys/devices/platform/usb_bam/enable
echo 0 > /sys/class/android_usb/android$num/enable
echo 0x900a > /sys/class/android_usb/android$num/idProduct
echo 0x05C6 > /sys/class/android_usb/android$num/idVendor
echo diag > /sys/class/android_usb/android0/f_diag/clients
echo tty,smd > /sys/class/android_usb/android0/f_serial/transports
echo smd,bam2bam > /sys/class/android_usb/android0/f_rmnet/transports
echo diag,serial,rmnet,mass_storage,audio > /sys/class/android_usb/android$num/functions
echo 1 > /sys/class/android_usb/android$num/enable

