#!/bin/sh

# DESCRIPTION: DIAG + ADB + QMI_RMNET (Android)

echo "Switching to composition number 0x9022"

echo 0 > /sys/class/android_usb/android0/enable
echo 0x9022 > /sys/class/android_usb/android0/idProduct
echo 0x05C6 > /sys/class/android_usb/android0/idVendor
echo diag > /sys/class/android_usb/android0/f_diag/clients
echo SMD,BAM2BAM > /sys/class/android_usb/android0/f_rmnet/transports
echo diag,adb,rmnet > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/remote_wakeup
echo 1 > /sys/class/android_usb/android0/enable
