#!/bin/sh

# DESCRIPTION: RNDIS + DIAG + ADB [Android]

echo "Switching to composition number 0x902D"

echo 0 > /sys/class/android_usb/android0/enable 
echo 0x902D > /sys/class/android_usb/android0/idProduct
echo 0x05C6 > /sys/class/android_usb/android0/idVendor
echo diag > /sys/class/android_usb/android0/f_diag/clients
echo rndis,diag,adb > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/remote_wakeup
echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
echo 1 > /sys/class/android_usb/android0/enable
