#!/bin/sh

# DESCRIPTION: DIAG + NMEA + MDM + MBIM [AMSS]

echo "Switching to composition number 0x9043"

echo 0 > /sys/class/android_usb/android0/enable
echo 0x9043 > /sys/class/android_usb/android0/idProduct
echo 0x05C6 > /sys/class/android_usb/android0/idVendor
echo 239 > /sys/class/android_usb/android0/bDeviceClass
echo 2 > /sys/class/android_usb/android0/bDeviceSubClass
echo 1 > /sys/class/android_usb/android0/bDeviceProtocol
echo diag > /sys/class/android_usb/android0/f_diag/clients
echo tty,smd > /sys/class/android_usb/android0/f_serial/transports
echo diag,serial,usb_mbim > /sys/class/android_usb/android0/functions
echo 1 > /sys/class/android_usb/android0/remote_wakeup
echo 1 > /sys/class/android_usb/android0/enable
