#!/bin/sh

# DESCRIPTION: DIAG + ADB + MODEM + QMI_RMNET : ECM : MBIM

echo "Switching to composition number 0x9064"

if [ "$1" = "y" ]; then
	num="1"
	mode="hsic"
else
	num="0"
	mode="hsusb"
fi

echo $mode > /sys/devices/platform/usb_bam/enable
echo 0 > /sys/class/android_usb/android$num/enable
echo 0x9064 > /sys/class/android_usb/android$num/idProduct
echo 0x05C6 > /sys/class/android_usb/android$num/idVendor
echo 239 > /sys/class/android_usb/android$num/bDeviceClass
echo 2 > /sys/class/android_usb/android$num/bDeviceSubClass
echo 1 > /sys/class/android_usb/android$num/bDeviceProtocol
echo smd > /sys/class/android_usb/android0/f_serial/transports
echo smd,bam2bam > /sys/class/android_usb/android0/f_rmnet/transports
echo diag,adb,serial,rmnet:ecm_qc:usb_mbim > /sys/class/android_usb/android$num/functions
echo 1 > /sys/class/android_usb/android$num/remote_wakeup
echo 1 > /sys/class/android_usb/android$num/enable

